##################################### USER #####################################

### register user
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
    "username": "aus20",
    "email": "aus20@gmail.com",
    "password": "password20"
}

### user login
POST http://localhost:8080/api/auth/signin
Content-Type: application/json
# Authorization: Bearer 

{
    "username": "aus4",
    "password": "password"
}

### get current logged in user
GET http://localhost:8080/api/auth/currentuser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhdXMxIiwiaWF0IjoxNjY1MTQwNDkyLCJleHAiOjE2NjUxNDQwOTJ9.gvF0GuWpyzDLJyaCz9LgxEQV77yiJPhZ-FeWxQf7g2VpGQsZpfEkRHgclLqWDh1dipdYcQdjN_1nJZH8nAwm9A

### get all users
GET http://localhost:8080/api/v1/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhdXMxIiwiaWF0IjoxNjY1MTQwNDkyLCJleHAiOjE2NjUxNDQwOTJ9.gvF0GuWpyzDLJyaCz9LgxEQV77yiJPhZ-FeWxQf7g2VpGQsZpfEkRHgclLqWDh1dipdYcQdjN_1nJZH8nAwm9A
### get user 1
GET http://localhost:8080/api/v1/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhdXMxIiwiaWF0IjoxNjY1MTQwNDkyLCJleHAiOjE2NjUxNDQwOTJ9.gvF0GuWpyzDLJyaCz9LgxEQV77yiJPhZ-FeWxQf7g2VpGQsZpfEkRHgclLqWDh1dipdYcQdjN_1nJZH8nAwm9A
### delete user 4
DELETE http://localhost:8080/api/v1/users/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhdXMxIiwiaWF0IjoxNjY1MTQwNDkyLCJleHAiOjE2NjUxNDQwOTJ9.gvF0GuWpyzDLJyaCz9LgxEQV77yiJPhZ-FeWxQf7g2VpGQsZpfEkRHgclLqWDh1dipdYcQdjN_1nJZH8nAwm9A
# Content-Type: application/json
# Authorization: Basic admin goodpassword

#  {
#      "email": "user@email.com",
#      "password": "password",
#      "authorities": "ROLE_USER"
#  }

### edit user 2
PUT http://localhost:8080/api/v1/users/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhdXMxIiwiaWF0IjoxNjY1MTQwNDkyLCJleHAiOjE2NjUxNDQwOTJ9.gvF0GuWpyzDLJyaCz9LgxEQV77yiJPhZ-FeWxQf7g2VpGQsZpfEkRHgclLqWDh1dipdYcQdjN_1nJZH8nAwm9A
{
    "username": "aus2",
    "email": "aus2@gmail.com",
    "password": "password"
}




##################################### ITEM #####################################

### add item
POST http://localhost:8080/api/v1/items/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhdXM0IiwiaWF0IjoxNjY2MjQ1MzI4LCJleHAiOjE2NjYyNDg5Mjh9._foY8NFoVhPuocp79XPx-RQfOA_V7yoOK7VAKz6v3m2GWVNHANSB_AymcDmPjKZRNgfGbwine8up3zBIWr_-0Q

{
    "itemName": "baked beans",
    "price": 5.00,
    "brand": "fair",
    "description": "yumz",
    "expiry_date": "10/11/2022",
    "type":"Canned food",
    "quantity": 5,
    "url": "https://media.nedigital.sg/fairprice/fpol/media/images/product/XL/10829840_XL1_20210915.jpg?w=1200&q=70"
}

### get all items
GET http://localhost:8080/api/v1/items
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhdXM0IiwiaWF0IjoxNjY2MDgwNTMxLCJleHAiOjE2NjYwODQxMzF9.U2MOvrheydz1OojNhav_y41xErvD2EbuOO5J1vWosoIc1MEsdxjqbCRRa0XAqgIgEcP9kSb0A3dPmMjB0ea30Q
### get item id 7
GET http://localhost:8080/api/v1/items/13
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhdXMxIiwiaWF0IjoxNjY1MTQwNDkyLCJleHAiOjE2NjUxNDQwOTJ9.gvF0GuWpyzDLJyaCz9LgxEQV77yiJPhZ-FeWxQf7g2VpGQsZpfEkRHgclLqWDh1dipdYcQdjN_1nJZH8nAwm9A

### get item type vegetable
GET http://localhost:8080/api/v1/items/type/vegetable
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhdXM0IiwiaWF0IjoxNjY2MjU1MTA2LCJleHAiOjE2NjYyNTg3MDZ9.CLxshTHgE1h3u9al-Wk9CzThswgRKI7Wu1Ul3LsL7XohyYEFHLZ_M_JFwELbvVhaXBjJOaRPIpXSTHdsRMcC1w

### delete item id 7
DELETE http://localhost:8080/api/v1/items/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhdXMyIiwiaWF0IjoxNjY1NDUzMzc5LCJleHAiOjE2NjU0NTY5Nzl9.9ih1u6oXS6AjINcJA-Bf5HJpRC-wu1HUpCQrhwxt15M-nIXYi3Gsv3s2hbrJKayMOrXwedIDFhJ815S4-KAECQ
### edit item id 9
PUT http://localhost:8080/api/v1/items/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhdXMyIiwiaWF0IjoxNjY1NDUzNDMzLCJleHAiOjE2NjU0NTcwMzN9.N_61iY9moeFIrQh8hE5e6N0VsmjwyOyC1cQdgtQxaUV1zGraIpPn9iW93XLh7wS3sw3s8Am8eh6Vvz7MYqpFRw
### get item type fruit
GET http://localhost:8080/api/v1/items/type/fruit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhdXM0IiwiaWF0IjoxNjY2MjQ5NTQ0LCJleHAiOjE2NjYyNTMxNDR9.loSqSO9I8-be0yn9HYvGATzrFEk909IuwgZ_0zGZAv97ZsOqji8N44Ls4KdXI1a8NBea7sbv6Sy-Wjx_BVhapg


{
    "itemName": "Watermelon",
    "price": 2,
    "brand": "fairprice",
    "description": "juicy",
    "expiry_date": "21/12/2022",
    "type":"fruit",
    "quantity": 10,
    "url": "https://images.heb.com/is/image/HEBGrocery/000320934"
}




##################################### CART #####################################

### get user's cart
GET http://localhost:8080/api/v1/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhdXMiLCJpYXQiOjE2NjYwMDM2NTMsImV4cCI6MTY2NjAwNzI1M30.DQaj-ituc6hz68h1EQf-KZh2g1FvvoAKq95G2fE5rgy-yGQfSmKuJu5E8Qps5Ya-2WE2LdJzczAqCdymU-6ThQ
### delete user's cart
DELETE http://localhost:8080/api/v1/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhdXMiLCJpYXQiOjE2NjYwMDM2NTMsImV4cCI6MTY2NjAwNzI1M30.DQaj-ituc6hz68h1EQf-KZh2g1FvvoAKq95G2fE5rgy-yGQfSmKuJu5E8Qps5Ya-2WE2LdJzczAqCdymU-6ThQ

### user add an item to cart (../cart/add/item_id)
POST http://localhost:8080/api/v1/cart/add/8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhdXMxIiwiaWF0IjoxNjY1MTQwNDkyLCJleHAiOjE2NjUxNDQwOTJ9.gvF0GuWpyzDLJyaCz9LgxEQV77yiJPhZ-FeWxQf7g2VpGQsZpfEkRHgclLqWDh1dipdYcQdjN_1nJZH8nAwm9A
### user edit cart item quantity (../cart/update/item_id/quantity)
PUT http://localhost:8080/api/v1/cart/update/8/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhdXMxIiwiaWF0IjoxNjY1MTQwNDkyLCJleHAiOjE2NjUxNDQwOTJ9.gvF0GuWpyzDLJyaCz9LgxEQV77yiJPhZ-FeWxQf7g2VpGQsZpfEkRHgclLqWDh1dipdYcQdjN_1nJZH8nAwm9A
### user delete item from cart (../cart/delete/item_id)
DELETE http://localhost:8080/api/v1/cart/delete/8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJyeWFuMSIsImlhdCI6MTY2NTEzMDE4NCwiZXhwIjoxNjY1MTMzNzg0fQ.i7_uQRuAbpVy6RDpQjWVLzEgACPIuLkvWmf_Zd18-7sJ_mKty0b3iqFwCw9X0TPHY4HAFOwpGod7QxJCTbYoXQ




##################################### ORDER #####################################

### get user's order history
GET http://localhost:8080/api/v1/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJub3RhdXMiLCJpYXQiOjE2NjYzMTUyODMsImV4cCI6MTY2NjMxODg4M30.TwQI-Wt7-ORk8TIjHSS5sMmNbj24DB_TU0Q9ey5JuUDIIdNGy1JW_yJ_athFm_CX9I0jBDwstQkVzxuucsh1WA

### user confirms card order and order is recorded in order history and removed from cart (../order/add)
POST http://localhost:8080/api/v1/order/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhaXJwb2QiLCJpYXQiOjE2NjY2ODQ2MzEsImV4cCI6MTY2NjY4ODIzMX0._olYYRtNWnOGVu-PFpMK9lpxhJrlQ9ywg6yACkPnWC88gvgdurK9OLGr6sGF2UZmhARpc1yYgdmk_9j8t-2Nzw
# ### user cancel order (../order/delete/order_id)
# DELETE http://localhost:8080/api/v1/cart/delete/219
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJub3RhdXMiLCJpYXQiOjE2NjYzMTQ1NzMsImV4cCI6MTY2NjMxODE3M30.5bLjP0LRn0nnATLIYMewZQ-iUMpf7JhZI5OEqiiBcUqO6mpP2xQCCa5R3jcW3RChKpIGHU7WiYIssqNyWisGpQ





##################################### OTHER STUFF #####################################
### get all users carbon saved
GET http://localhost:8080/api/v1/ordertotalcarbon
Content-Type: application/json

### get total user count
GET http://localhost:8080/api/v1/totalusers
Content-Type: application/json
