##################################### USER #####################################

### register user
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
    "username": "aus2",
    "email": "aus2@gmail.com",
    "password": "password"
}

### user login
POST http://localhost:8080/api/auth/signin
Content-Type: application/json
# Authorization: Bearer 

{
    "username": "aus",
    "password": "password"
}

### get current logged in user
GET http://localhost:8080/api/auth/currentuser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhdXMyIiwiaWF0IjoxNjY0ODA4MjI0LCJleHAiOjE2NjQ4OTQ2MjR9.NhPEM2f7-0jzFM7DZFG2iVKXf-xnCsrFTDXmCTK3suQvsmQFxqDXrIIAZEJqqz1p0S1YCo6UcCvJpYimgrgrwg


### get all users
GET http://localhost:8080/api/v1/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhdXMyIiwiaWF0IjoxNjY0NzgwMDE4LCJleHAiOjE2NjQ4NjY0MTh9.OFdb6Y7oOcL0pS2qVrJlM8NF0uXydYOaPHKJcTs_4xzROchZr02fOifTTimsbv1qLrc0tJrDSLhmMFqMH9jinw

### get user 1
GET http://localhost:8080/api/v1/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhdXMyIiwiaWF0IjoxNjY0NzgwMDE4LCJleHAiOjE2NjQ4NjY0MTh9.OFdb6Y7oOcL0pS2qVrJlM8NF0uXydYOaPHKJcTs_4xzROchZr02fOifTTimsbv1qLrc0tJrDSLhmMFqMH9jinw

### delete user 4
DELETE http://localhost:8080/api/v1/users/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhdXMyIiwiaWF0IjoxNjY0NzgwMDE4LCJleHAiOjE2NjQ4NjY0MTh9.OFdb6Y7oOcL0pS2qVrJlM8NF0uXydYOaPHKJcTs_4xzROchZr02fOifTTimsbv1qLrc0tJrDSLhmMFqMH9jinw

# Content-Type: application/json
# Authorization: Basic admin goodpassword

#  {
#      "email": "user@email.com",
#      "password": "password",
#      "authorities": "ROLE_USER"
#  }

### edit user 2
PUT http://localhost:8080/api/v1/users/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhdXMyIiwiaWF0IjoxNjY0NzgwMDE4LCJleHAiOjE2NjQ4NjY0MTh9.OFdb6Y7oOcL0pS2qVrJlM8NF0uXydYOaPHKJcTs_4xzROchZr02fOifTTimsbv1qLrc0tJrDSLhmMFqMH9jinw
{
    "username": "aus2",
    "email": "aus2@gmail.com",
    "password": "password"
}




##################################### ITEM #####################################

### add item
POST http://localhost:8080/api/v1/items/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhdXMiLCJpYXQiOjE2NjQ3OTM3NjMsImV4cCI6MTY2NDg4MDE2M30.Sg3SID1PGUqpiRYCpwCP4Y4ZowgxDbUhhXZ8RQ_XyG-Da9ZrSU5fPlqNtFQih4pwF73jk8EdM7-diPAQaKubHA

{
    "itemName": "Dried pitted prunes",
    "price": 3,
    "brand": "Sunsweet",
    "description": "delicious",
    "expiry_date": "12/12/2022",
    "type":"healthy snacks"
}

### get all items
GET http://localhost:8080/api/v1/items
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhdXMyIiwiaWF0IjoxNjY0Nzg1Nzk5LCJleHAiOjE2NjQ4NzIxOTl9.pEikfXYdVoW6onKOhFQ6d7UwBw7yzeR1YVAjmisobw6C6hLh2ZfotlLATJ4Fhf-MspXIpfzVYBpb0n6AVDMwLg

### get item id 7
GET http://localhost:8080/api/v1/items/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhdXMyIiwiaWF0IjoxNjY0Nzg1Nzk5LCJleHAiOjE2NjQ4NzIxOTl9.pEikfXYdVoW6onKOhFQ6d7UwBw7yzeR1YVAjmisobw6C6hLh2ZfotlLATJ4Fhf-MspXIpfzVYBpb0n6AVDMwLg

### delete item id 7
DELETE http://localhost:8080/api/v1/items/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhdXMyIiwiaWF0IjoxNjY0Nzg1Nzk5LCJleHAiOjE2NjQ4NzIxOTl9.pEikfXYdVoW6onKOhFQ6d7UwBw7yzeR1YVAjmisobw6C6hLh2ZfotlLATJ4Fhf-MspXIpfzVYBpb0n6AVDMwLg

### edit item id 9
PUT http://localhost:8080/api/v1/items/9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhdXMyIiwiaWF0IjoxNjY0Nzg1Nzk5LCJleHAiOjE2NjQ4NzIxOTl9.pEikfXYdVoW6onKOhFQ6d7UwBw7yzeR1YVAjmisobw6C6hLh2ZfotlLATJ4Fhf-MspXIpfzVYBpb0n6AVDMwLg

{
    "itemName": "Lays Potato Chips",
    "price": 1,
    "brand": "Lays",
    "description": "Crispy crisps",
    "expiry_date": "21/10/2022",
    "type":"tibits"
}




##################################### CART #####################################

### get user's cart
GET http://localhost:8080/api/v1/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhdXMiLCJpYXQiOjE2NjQ4MDgzODUsImV4cCI6MTY2NDg5NDc4NX0.cgPxATSIXe87EfPyDYqfvsHVW7r2l6xU4Fp0FVQYosHz3LB7_4gWCiKFcNFjUcrvTOBZns7gjB9aqCY_er9YOg

### user add item to cart
POST http://localhost:8080/api/v1/cart/add/2/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhdXMiLCJpYXQiOjE2NjQ4MDgzODUsImV4cCI6MTY2NDg5NDc4NX0.cgPxATSIXe87EfPyDYqfvsHVW7r2l6xU4Fp0FVQYosHz3LB7_4gWCiKFcNFjUcrvTOBZns7gjB9aqCY_er9YOg